apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui-2
spec:
  ports:
  - port: 8054
    targetPort: 8054
  selector:
    app: guestbook-ui
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui-3
spec:
  ports:
  - port: 8083
    targetPort: 8083
  selector:
    app: guestbook-ui
