apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui-veruy-long-name-for-service-to-check-the-bug-1
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui-veruy-long-name-for-service-to-check-the-bug-2
spec:
  ports:
  - port: 8054
    targetPort: 8054
  selector:
    app: guestbook-ui
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui-veruy-long-name-for-service-to-check-the-bug-3
spec:
  ports:
  - port: 8083
    targetPort: 8083
  selector:
    app: guestbook-ui
